package com.stefansavev.randomprojections.implementation

import com.stefansavev.randomprojections.implementation.bucketsearch.BucketSearchSettings

case class BruteForceSignatureSearch() extends BucketSearchSettings
