files_location <- 'D:/RandomTreesData-144818512896186816/input/mnist'

kaggle_train_file <- paste(files_location, 'originaldata/train.csv', sep = "/")
kaggle_test_file <- paste(files_location, 'originaldata/test.csv', sep = "/")
output_train_svd <- paste(files_location, 'svdpreprocessed/train.csv', sep = "/")
output_test_svd <- paste(files_location, 'svdpreprocessed/test.csv', sep = "/")

#generated by the scala program
predictions_file <- "D:/RandomTreesData-144818512896186816/output/mnist/predictions-test.csv"

train_data <- read.csv(kaggle_train_file, header = T, sep = ",")

without_labels <- which(names(train_data) != "label")
label_col_index <- which(names(train_data) == "label")[1]

train_matrix <- sqrt(data.matrix(train_data[,without_labels]))

num_examples <- dim(train_matrix)[1]
AtA <- (t(train_matrix) %*% train_matrix)/num_examples
s <- svd(AtA)

num_sing_vectors = 100
reduced_data <- train_matrix %*% s$v[, 1:num_sing_vectors]
dim(reduced_data)

s_corr <- 1/(sqrt(s$d[1:num_sing_vectors] + 10000))
r <- s$v[, 1:num_sing_vectors] %*% diag(s_corr)

r_inv <- diag(sqrt(s$d[1:num_sing_vectors] + 10000)) %*% t(s$v[, 1:num_sing_vectors])

reduced_data_alt <- train_matrix %*% r

labels <- train_data[,label_col_index]

with_labels <- cbind(labels, reduced_data_alt)
colnames(with_labels) <- c("label", paste("f", 1:100, sep=""))

write.table(with_labels, file=output_train_svd, quote=FALSE, col.names = TRUE, row.names = FALSE, sep = ",")


test_data <- read.csv(kaggle_test_file, header = T, sep = ",")
without_labels_test <- which(names(test_data) != "label")
test_matrix <- sqrt(data.matrix(test_data[,without_labels_test]))

reduced_test <- test_matrix %*% r
test_labels <- rep(0, dim(test_data)[1])
test_with_labels <- cbind(test_labels, reduced_test)
colnames(test_with_labels) <- c("label", paste("f", 1:100, sep=""))

write.table(test_with_labels, file=output_test_svd, quote=FALSE, col.names = TRUE, row.names = FALSE, sep = ",")

#verify the predictions manually after running the tool

predictions <- read.csv(predictions_file, header = T, sep = ",")

example_id <- 4
image(1:28, 1:28, matrix(1.0 - test_matrix[predictions[example_id,1], ]/sqrt(255), nrow = 28, byrow = T))
print(predictions[example_id,2])